### ISSUE TITLE
Future Neighborhood Studies are being zeroed out

### ISSUE THREAD

**Issue by mshapiro1** [NYCPlanning/db-knownprojects#175]
Every project from source "Future Neighborhood Studies" currently shows units_net as 0. Units_Net for these projects should always equal Units_Gross.

**Comment by mgraber** [comment]
### Debugging notes
The `units_net` for dcp_n_study_projected_proj records and dcp_n_study_future_proj records get assigned in [add_remaining_n_study.sql](https://github.com/NYCPlanning/db-knownprojects/blob/master/knownprojects_build/sql/add_remaining_n_study.sql). Final output has NULL for `units_gross`, despite this step. Note that records are only added when the `record_id` does not already exist in kpdb, which is initially created in [resolve_clusters.py](https://github.com/NYCPlanning/db-knownprojects/blob/master/knownprojects_build/python/resolve_clusters.py)

- Check that kpdb gets deleted and recreated with each run of [04_build_kpdb.sh](https://github.com/NYCPlanning/db-knownprojects/blob/master/knownprojects_build/04_build_kpdb.sh). One possibility is that logic for these records isn't getting applied because the record_id already exists.
- Check that any SQL scripts ocurring after add_remaining_n_study.sql do not modify `units_net`.

**Comment by mgraber** [comment]
Error identified: [add_remaining_n_study.sql](https://github.com/NYCPlanning/db-knownprojects/blob/master/knownprojects_build/sql/add_remaining_n_study.sql) does not account for the addition of the borough field.
