### ISSUE TITLE
Track corrections applied

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#232]
Use either a dcp_edited field or corrections_applied table to track where records have been edited.

**Comment by SPTKL** [comment]
let's try to write a stored procedure that loops through each row of the corrections, and if correction applies, add the correction record to the "applied_correction", if not, add the correction record to the "not_applied_correction" table.

we can handle dynamic type casting using `select pg_typeof(column)`

**Comment by mgraber** [comment]
https://github.com/NYCPlanning/edm-overview/issues/576

**Comment by SPTKL** [comment]
So i'm thinking of something that corrects row by row instead of applying a entire category. 

e.g. `CALL correction('combined', 'XXXXXXXXXXX', 'date', NULL, '2021-02-01')` 
combined -> target table
'XXXXXXXXXXX' -> record_id
date -> target field
NULL -> old_value
2021-02-01 -> new_value

this would give us better control because we can decided row by row if each correction record gets applied or not. 

step by step, the procedure would be: 
1. calculate the field type and store it in a variable
2. extract current value given table, record_id and field, store in a variable (current_value)
3. if current_value == old_value -> apply correction, add correction record to applied corrections
4. else -> do not apply correction and add correction record to not applied corrections

**Comment by SPTKL** [comment]
## Sample usage
```sql
DO $$
DECLARE 
    _record_id text;
    _field text;
    _old_value text;
    _new_value text;
BEGIN
    FOR _record_id, _field, _old_value, _new_value IN 
        SELECT record_id, field, old_value, new_value 
        FROM kpdb_corrections.latest
        WHERE field NOT IN ('add', 'remove', 'project_id', 'units_net')
    LOOP
        CALL correction('combined', _record_id, _field, _old_value, _new_value);
    END LOOP;
END $$;
```
