### ISSUE TITLE
Spatial Corrections

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-knownprojects#278]
## option 1: 
1. we can ingest a `corrections_spatial.zip` -> a shapefile in a stable schema provided by HED 
2. in create_corrections.sql, we load it as a temporary table and merge on to corrections_main
3. we will have a github action to covnert  `corrections_spatial.zip` to `corrections_spatial.csv` in `db-knownprojects-data` and commit back into the corrections folder

## option 2: 
HED:
1. HED upload spatial files to carto
2. download as csv with wkb geometry
3. save the file into a csv, named `corrections_spatial.csv`, in `db-knownprojects-data` 

DE:
~4. we read and merge onto corrections_main #324~
5. overwrite geometries based on record_id #325

**Comment by td928** [comment]
I think we are probably going with option 2. It does seem a little more ad-hoc in terms of the new file created. But we think this is conceptually most simplistic. Just to clarify a little more about option 2 though, I don't know if step 4 'merge onto corrections_main' is necessary since we would just upload new spatial source file each time some corrections are made. Is my understanding correct?

**Comment by SPTKL** [comment]
@td928  you can ignore 4, we will do it in our process

**Comment by td928** [comment]
sounds good! @SPTKL
