### ISSUE TITLE
Questions from HED

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#301]
- [x] Are we pulling deactivated BBLs from ZAP? 
> We've changed the code to exclude deactivated BBLs #315 
- [x] ~~Alter the geometry intersection criteria to NOT include records that are only touching boundaries~~
> See #307. Won't fix.

**Comment by td928** [comment]
Hi I think our questions is not exactly what Baiyue's response is about. Our questions is if in the process of pulling ZAP records there was filter for 'inactive' ZAP bbls, which is related to the deactivate action in ZAP.

**Comment by SPTKL** [comment]
@td928 we can't tell if a BBL is active vs inactive, I don't know about the deactivate action in ZAP, so we cannot differentiate active/inactive ZAP BBL.

**Comment by td928** [comment]
Hi EDM  @SPTKL @mgraber thank you for the push last week to make the enhancements for. However, in lights of reviewing the new output table for the [final KPDB table](https://github.com/NYCPlanning/db-knownprojects-data/blob/output-20210617-1714/output/kpdb.csv.zip), we do notice some major issues that needs to be addressed. 

1. Units net issue. The field units_net is blank for large swath of the final kpdb table currently. According to the definition we found in the [wiki](https://github.com/NYCPlanning/db-knownprojects/wiki/KPDB-Schema), we believe that this should not be the case. And particularly we deduce from that most of the projected units (e.g. the prop_within_5_years) are based the units_net field, so this will cause issues down the line as well.  

2. DOB units deduplication problem. We can cite two examples here to help illustrate the issue namely **270 Nostrand** and **824 Metropolitan**. For the 270 Nostrand, the DOB records suggests that there are _241 units_ permitted. Then for the ZAP record, after deduplication, it should allocate _246 units_ (_units gross 487_ - _units permitted 241_) to the units_net field and then further distribute according to the phasing assumption.

3. Phasing assumption about permitted project. This is more a minor issue where 270 Nostrand also illustrated that the phasing assumption for permitted units should fall under the within 5 years range.

Thank you! Please let me know if you have any questions about these issues.

**Comment by td928** [comment]
Hey  EDM @NYCPlanning/data-engineering ! Upon reviewing the [new output](https://github.com/NYCPlanning/db-knownprojects-data/tree/output-20210624-1404/output), we do notices another issue. Currently, the neighborhood study projected development sites seem to be pulling from the wrong source files. As the names of those records suggest(e.g. East New York Rezoning Commitment 6), it seems that they are duplicates of the rezoning study commitment sites. This might be due to a miscommunication earlier and the correct source files to use for the projected development sites are the same as last year and they can be found in this [folder](https://nyco365.sharepoint.com/sites/NYCPLANNING/hed/Shared%20Documents/Forms/AllItems.aspx?viewid=4e2d0d84%2D0e1a%2D460a%2Db248%2Da7f1048f5261&id=%2Fsites%2FNYCPLANNING%2Fhed%2FShared%20Documents%2F01%20Projects%5Factive%2FHousing%20%28only%20current%20items%29%2FKPDB%2FInputs%20Collection%202021%2FKPDB%202021%20Input%20Data%20provided%20to%20EDM%2FNeighborhood%20study%20projected%20development%20sites). This will be an important change because we are removing all neighborhood rezoning records from ZAP and instead only rely on those projected development sites to provide

Also a much more minor issue, there are currently multiple copies for Gowanus Future Rezoning Development in the final output. Their record ids are identical and also they are almost the only duplicated records in the entire output table. 

Thank you! Please let me know if you have any questions about those two issues.

**Comment by SPTKL** [comment]
@td928  please specify the correct filename for neighborhood study projected development site

**Comment by td928** [comment]
Good morning @SPTKL @mgraber ! I think i was able to locate the issue with the current but still seeking for a solution at the moment. After getting all the intermediate tables from clustering, I was able to narrow the issue to the this query in the clustering step. 

https://github.com/NYCPlanning/db-knownprojects/blob/57ff42d33bea4d2d579970a191345a265c95fc05/sql/_project_record_ids.sql#L36-L45

For one instance, P2018R0253 and 2019R0295, the two records are correctly identified by the dbscan step that they are clusters and still joined together in the project_record_join step. But then the all_intersections do not return any geometry for this cluster and they are consequently broken up in the last step by the [ST_overlap statement](https://github.com/NYCPlanning/db-knownprojects/blob/57ff42d33bea4d2d579970a191345a265c95fc05/sql/_project_record_ids.sql#L50). I am not quite sure what exactly why but my guess now is in cases where one geometry is completely within another the [ST_Intersection](https://postgis.net/docs/ST_Intersection.html) does not behave as we expect.  Please take a look at [this batch output](https://github.com/NYCPlanning/db-knownprojects-data/tree/output-20210712-2010/output/review) with all the intermediate tables for more details. I am thinking about the solutions for this. Please let me know if you have any suggestions! Thank you very much!
