### ISSUE TITLE
ZAP project description for review tables

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#63]
Keep ZAP project description in the cluster 1 review table and include in the DOB project review table

**Comment by mgraber** [comment]
Full description fields cannot easily be imported into postgres from CARTO, because the variety of special characters in the large chunks of text reliable eliminates options for a delimiter.

To include the full description in both review tables:
1. Read completed cluster review tables into pandas using cartoframes

**Round 1 review: Clusters**

2. Drop description columns using python
3. Dump cluster review tables to postgres without the description columns
4. Generate DOB review table
5. Load DOB review table to pandas
6. Load a description look-up table to pandas
7. Re-merge description with DOB review table using pandas
8. Push to CARTO using cartoframes

**Round 2 review: DOB matches**

9. Read completed DOB review tables to pandas using cartoframes
10. Again drop description field using python
11. Dump reviewed DOB matches to postgres without description field
12. Incorporate reviewed DOB matches in postgres

**Comment by AmandaDoyle** [comment]
Note: We may not use project description.  We should be using the project brief, which is on the website
