### ISSUE TITLE
DOB review table change "inactive" to “DOB_inactive” 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#80]
HED requests the “inactive” field to be changed to “DOB_inactive"

**Comment by mgraber** [comment]
In the conversation about dates and ZAP matching on April 27, we discussed potentially using `inactive` to also flag ZAP projects. 

Before changing this field name, can we verify that is isn't useful for other types of records?

@levysamu @mshapiro1

**Comment by mshapiro1** [comment]
@mgraber for the 2020 KPDB, inactive should only refer to select DOB jobs. HED in the future (maybe 2021) may run analyses to define what is an "inactive" ZAP job. 

If that means it's easier to identify "inactive" as "inactive" instead of "DOB_inactive," that's fine with CP.

Looking for confirmation @levysamu

**Comment by AmandaDoyle** [comment]
@mshapiro1 @levysamu If "inactive" may be used for more than just DOB records I advocate to keep the field name "inactive" and not "DOB_inactive"

**Comment by mshapiro1** [comment]
Works for me

**Comment by AmandaDoyle** [comment]
@levysamu we're still looking for your signoff here

**Comment by levysamu** [comment]
If we are planning on using the Inactive field for other sources then yes, we can leave it as simply Inactive.

**Comment by mgraber** [comment]
Conclusion: Leave `inactive` field as is.
