### ISSUE TITLE
future_city -- Future city-sponsored RFPs/RFEIs

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-knownprojects#9]
#### dataset alias: fcity_rfp ?
- [x] dataloading
- [x] geocoding
    1. Extract addresses from project names
- [ ] deduplication

**Comment by mgraber** [comment]
Ignore addresses and alter to get BBL-level polygon geometry

**Comment by baolingz** [comment]
@mshapiro1 Some records have `NULL` for `total_units`. I noticed some other records are labeled with `missing` under `total_units`. For `NULL` cases, are there ways to backfill them?

**Comment by mshapiro1** [comment]
@baolingz there is no way to backfill those projects because we never had information from them. this sheet had lots of manual research go into the few projects we could identify, and we only filled in information for those projects. We then uploaded the whole spreadsheet and filtered the list to just projects which had information.

The code for the above is available here: https://github.com/NYCPlanning/Known-Projects-Database/blob/master/1f.%20Relevant_Projects_Public_Sites.sql

Filtering script below:

`(select * from capitalplanning.table_190510_public_sites_ms_v3_1 where project_found_in = '' and omit_from_public_sites_relevant_projects = 0 /*Selecting public sites not accounted for in other sources*/)`
